### ISSUE TITLE
Eliminazione pubblicità

### ISSUE THREAD

**Issue by rasky** [italia/docs-italia-theme#5]
D'accordo con gli autori di RTD, dobbiamo inserire il seguente stile per disattivare definitivamente le pubblicità dai nostri repo:

```css
    div.rst-pro {
        display: none !important;
    }
```
